#!/usr/bin/env python3
"""
Qdrant Server Setup — run once on a fresh server to install and configure Qdrant.

Supports:
  * Local binary (no Docker) — systemd service, firewall, storage tuning
  * Docker Compose — for easy single-node or HA multi-node
  * Cloud provider one-liners — DigitalOcean, Hetzner, AWS EC2

Usage:
  sudo python3 setup_qdrant_server.py          # Interactive
  sudo python3 setup_qdrant_server.py --docker  # Docker mode
  sudo python3 setup_qdrant_server.py --help   # Full options
"""
import argparse
import os
import shutil
import subprocess
import sys
import urllib.request
import urllib.error
from pathlib import Path

# ── helpers ───────────────────────────────────────────────────────────────────

def run(cmd, check=True, capture=False, timeout=120):
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=capture, text=True, timeout=timeout)
    if check and result.returncode != 0:
        print(f"  ✗ exit {result.returncode}: {result.stderr.strip()}")
        sys.exit(1)
    return result.stdout.strip() if capture else ""


def exists(cmd):
    return shutil.which(cmd) is not None


SYSTEMD_DIR   = Path("/etc/systemd/system")
QDRANT_USER   = "qdrant"
QDRANT_GROUP  = "qdrant"
QDRANT_HOME   = Path("/opt/qdrant")
QDRANT_DATA   = Path("/var/lib/qdrant")
QDRANT_CONFIG = QDRANT_HOME / "config.yaml"
QDRANT_BINARY = QDRANT_HOME / "qdrant"
SERVICE_FILE  = SYSTEMD_DIR / "qdrant.service"

GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
RESET  = "\033[0m"


def ok(msg):
    print(f"{GREEN}✓{RESET} {msg}")


def warn(msg):
    print(f"{YELLOW}!{RESET} {msg}")


def info(msg):
    print(f"  {msg}")


# ── pre-flight ────────────────────────────────────────────────────────────────

def check_root():
    if os.geteuid() != 0:
        print(f"{RED}ERROR:{RESET} must run as root (sudo)")
        sys.exit(1)


def detect_os():
    if Path("/etc/debian_version").exists():
        return "debian"
    if Path("/etc/redhat-release").exists():
        return "rhel"
    if Path("/etc/alpine-release").exists():
        return "alpine"
    return "unknown"


def install_packages(packages):
    os_name = detect_os()
    if os_name == "debian":
        run(["apt-get", "update", "-qq"])
        run(["apt-get", "install", "-y", "-qq"] + packages)
    elif os_name == "rhel":
        run(["dnf", "install", "-y"] + packages)
    elif os_name == "alpine":
        run(["apk", "add"] + packages)
    else:
        warn(f"Unknown OS — attempting anyway with: {packages}")


def wait_for_qdrant(host, port, timeout=30):
    import time
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"http://{host}:{port}/collections", timeout=2) as r:
                if r.status == 200:
                    return True
        except Exception:
            pass
        time.sleep(1)
    return False


# ── binary install ────────────────────────────────────────────────────────────

def download_binary(version):
    arch = "x86_64-unknown-linux-musl.tar.gz"
    url = f"https://github.com/qdrant/qdrant/releases/download/{version}/qdrant-{arch}"
    tmp = Path(f"/tmp/{arch}")
    info(f"Downloading {url} …")
    run(["curl", "-fL", "-o", str(tmp), url], timeout=300)
    info(f"Extracting to {QDRANT_HOME} …")
    QDRANT_HOME.mkdir(parents=True, exist_ok=True)
    run(["tar", "-xzf", str(tmp), "-C", str(QDRANT_HOME), "--strip-components=1"])
    Path(tmp).unlink(missing_ok=True)
    ok("Binary installed")


def create_user():
    if exists("useradd"):
        run(["useradd", "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", QDRANT_USER], check=False)
    else:
        info("useradd not available — running as root")
    ok(f"User: {QDRANT_USER}")


def create_config(bind, port, storage_path, max_disk_gb):
    max_disk = f"\n  maximum_disk_space:\n    data: {max_disk_gb}" if max_disk_gb else ""
    content = f"""# Qdrant Configuration — generated by setup_qdrant_server.py
# Docs: https://qdrant.tech/documentation/guides/configuration/

service:
  host: {bind}
  port: {port}            # gRPC port
  http_port: {port + 1}  # REST API (port + 1){max_disk}

storage:
  storage_path: {storage_path}
  snapshots_path: {storage_path}/snapshots
  on_disk_payload: true   # Keep payload on disk (not in RAM)
  hnsw_config:
    m: 16                 # Links per node — higher = better recall, more RAM
    ef_construct: 128     # Index build width — higher = better recall, slower build
    full_scan_threshold: 10000
    on_disk: false
  optimizers:
    indexing_threshold: 20000
    flush_interval_sec: 5
    vacuum_min_vector_size: 16

cluster:
  enabled: false   # Enable for HA multi-node setups
"""
    QDRANT_CONFIG.write_text(content)
    ok(f"Config written → {QDRANT_CONFIG}")


def write_systemd_service():
    content = f"""[Unit]
Description=Qdrant Vector Database
Documentation=https://qdrant.tech/documentation/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={QDRANT_USER}
Group={QDRANT_GROUP}
ExecStart={QDRANT_BINARY} --config-path {QDRANT_CONFIG}
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths={QDRANT_DATA} {QDRANT_HOME}

[Install]
WantedBy=multi-user.target
"""
    SERVICE_FILE.write_text(content)
    info(f"Systemd unit → {SERVICE_FILE}")


def setup_permissions():
    QDRANT_DATA.mkdir(parents=True, exist_ok=True)
    if exists("chown"):
        run(["chown", "-R", f"{QDRANT_USER}:{QDRANT_GROUP}", str(QDRANT_DATA)], check=False)
    if exists("chmod"):
        run(["chmod", "750", str(QDRANT_DATA)], check=False)
    QDRANT_CONFIG.chmod(0o600)
    QDRANT_BINARY.chmod(0o755)
    ok("Permissions set")


def start_service():
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "qdrant"])
    run(["systemctl", "start", "qdrant"])
    ok("Service started & enabled")


def open_firewall(port):
    os_name = detect_os()
    if os_name == "debian" and exists("ufw"):
        run(["ufw", "--force", "enable"], check=False)
        run(["ufw", "allow", f"{port}/tcp"], check=False)
        run(["ufw", "allow", f"{port+1}/tcp"], check=False)
        ok(f"UFW: ports {port}, {port+1} opened")
    elif os_name == "rhel" and exists("firewalld"):
        run(["firewalld", "--permanent", f"--add-port={port}/tcp"], check=False)
        run(["firewalld", "--permanent", f"--add-port={port+1}/tcp"], check=False)
        run(["firewalld", "--reload"], check=False)
        ok(f"firewalld: ports {port}, {port+1} opened")


def install_binary(args):
    print("\n─── Installing Qdrant (binary) ───")
    create_user()
    download_binary(args.version)
    create_config(args.bind, args.port, str(QDRANT_DATA), args.max_disk_space_gb)
    write_systemd_service()
    setup_permissions()
    start_service()
    open_firewall(args.port)
    ok(f"Qdrant up — REST: http://{args.bind}:{args.port+1}  |  gRPC: {args.bind}:{args.port}")
    info(f"Config: {QDRANT_CONFIG}  |  Data: {QDRANT_DATA}")


# ── Docker install ─────────────────────────────────────────────────────────────

DOCKER_COMPOSE_TEMPLATE = """# Qdrant Docker Compose — generated by setup_qdrant_server.py
# For HA 3-node setup see: https://github.com/qdrant/qdrant/blob/master/lib/docker/docker-compose.single-node.yml
version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:{version}
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    # Performance flags (uncomment for large datasets):
    # environment:
    #   QDRANT__STORAGE__ON_DISK_PAYLOAD: "true"

volumes:
  qdrant_storage:
"""


def install_docker(args):
    print("\n─── Installing Qdrant (Docker) ───")
    if not exists("docker"):
        info("Docker not found — installing …")
        run(["curl", "-fsSL", "https://get.docker.com", "-o", "/tmp/get-docker.sh"], timeout=300)
        run(["sh", "/tmp/get-docker.sh"], timeout=300)
        run(["systemctl", "enable", "docker"], check=False)
        ok("Docker installed")
    compose = Path("/opt/qdrant/docker-compose.yml")
    compose.parent.mkdir(parents=True, exist_ok=True)
    compose.write_text(DOCKER_COMPOSE_TEMPLATE.format(version=args.version.lstrip("v")))
    info(f"Written → {compose}")
    run(["docker", "compose", "-f", str(compose), "up", "-d"], timeout=120)
    ok("Container started")
    info("REST: http://localhost:6333  |  gRPC: localhost:6334")


# ── cloud helpers ─────────────────────────────────────────────────────────────

def print_digitalocean_instructions():
    print("""
─── DigitalOcean App Platform ───────────────────────────────
  1. Go to: https://marketplace.digitalocean.com/apps/qdrant
  2. Or use doctl:
     doctl apps create \\
       --spec https://raw.githubusercontent.com/qdrant/qdrant/master/lib/docker/docker-compose.single-node.yml
────────────────────────────────────────────────────────────
""")


def print_hetzner_instructions():
    print("""
─── Hetzner Cloud ────────────────────────────────────────────
  1. Create a CX22 (2 vCPU / 4 GB) or CX32 instance
  2. SSH in and run as root:
     curl -fsSL https://get.docker.com | sh
     mkdir -p /opt/qdrant
     # Save docker-compose.yml to /opt/qdrant/ then:
     docker compose -f /opt/qdrant/docker-compose.yml up -d
  3. Open firewall ports 6333, 6334 in Hetzner Cloud Console
─────────────────────────────────────────────────────────────
""")


def print_aws_instructions():
    print("""
─── AWS EC2 ──────────────────────────────────────────────────
  1. Launch an EC2 instance (t3.medium minimum, Ubuntu 22.04 LTS)
  2. Security group: open TCP 6333, 6334
  3. SSH in and run:
     curl -fsSL https://get.docker.com | sh
     mkdir -p /opt/qdrant
     # Save docker-compose.yml to /opt/qdrant/ then:
     docker compose -f /opt/qdrant/docker-compose.yml up -d
─────────────────────────────────────────────────────────────
""")


# ── interactive prompts ─────────────────────────────────────────────────────

def ask(msg, default):
    val = input(f"  {msg} [{default}]: ").strip()
    return val or default


# ── main ─────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Qdrant server setup — install on a fresh VM (binary or Docker).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  sudo python3 setup_qdrant_server.py              # Interactive binary install
  sudo python3 setup_qdrant_server.py --docker    # Docker install
  sudo python3 setup_qdrant_server.py --cloud aws # AWS deployment guide
  sudo python3 setup_qdrant_server.py --non-interactive --version v1.8.0
        """
    )
    p.add_argument("--docker", action="store_true", help="Use Docker instead of binary")
    p.add_argument("--cloud", choices=["digitalocean", "hetzner", "aws"],
                   help="Print cloud provider deployment guide")
    p.add_argument("--version", default="v1.7.4", help="Qdrant version (default: v1.7.4)")
    p.add_argument("--bind", default="0.0.0.0", help="Bind address (default: 0.0.0.0)")
    p.add_argument("--port", type=int, default=6333, help="gRPC port (default: 6333)")
    p.add_argument("--max-disk-space-gb", type=int, default=0,
                   help="Max disk space per collection in GB (0 = unlimited)")
    p.add_argument("--non-interactive", action="store_true",
                   help="Use all defaults, skip all prompts")
    return p.parse_args()


def main():
    args = parse_args()
    print("=" * 60)
    print("  Qdrant Server Setup")
    print("=" * 60)

    if args.cloud:
        {
            "digitalocean": print_digitalocean_instructions,
            "hetzner": print_hetzner_instructions,
            "aws": print_aws_instructions,
        }[args.cloud]()
        return

    check_root()

    if not args.non_interactive:
        mode = input("\n  Mode: [binary] / docker / cloud: ").strip().lower()
        if mode == "docker":
            args.docker = True
        elif mode == "cloud":
            print("  Providers: digitalocean, hetzner, aws")
            provider = input("  Provider: ").strip().lower()
            {
                "digitalocean": print_digitalocean_instructions,
                "hetzner": print_hetzner_instructions,
                "aws": print_aws_instructions,
            }.get(provider, lambda: None)()
            return

    if not args.docker:
        if not args.non_interactive:
            args.bind = ask("Bind address", "0.0.0.0")
            args.port = int(ask("gRPC port", "6333"))
            args.max_disk_space_gb = int(ask("Max disk (GB, 0=unlimited)", "0")) or None
            args.version = ask("Qdrant version", "v1.7.4")
        install_binary(args)
    else:
        install_docker(args)

    # ── health check ────────────────────────────────────────────────────
    rest_port = args.port + 1
    bind_host = args.bind if args.bind != "0.0.0.0" else "localhost"
    print(f"\n[*] Waiting for Qdrant to respond on http://{bind_host}:{rest_port} …")
    if wait_for_qdrant(bind_host, rest_port):
        ok("Qdrant is healthy and responding.")
    else:
        warn("Qdrant did not respond in 30s — run: systemctl status qdrant")

    print("\n" + "=" * 60)
    print(f"  {GREEN}Setup complete!{RESET}")
    print("=" * 60)
    bind_for_export = args.bind if args.bind != "0.0.0.0" else "<server-ip>"
    print(f"\n  On your Hermes bot server(s), set:")
    print(f"    export QDRANT_HOST={bind_for_export}")
    print(f"    export BOT_ID=your-bot-name")
    print(f"    python ~/.hermes/skills/memory/vector-memory/references/setup_once.py")
    print()


if __name__ == "__main__":
    main()
